version: "3.7"

services:
  voard_db:
    image: mysql
    container_name: voard_db
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: java2_board
      MYSQL_USER: user1
      MYSQL_PASSWORD: dsaewq321!
      MYSQL_ROOT_PASSWORD: dsaewq321!
      TZ: Asia/Seoul
    ports:
      - 3309:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    command: [ "mysqld",
               "--character-set-server=utf8mb4",
               "--collation-server=utf8mb4_unicode_ci",
               "--default_authentication_plugin=mysql_native_password" ]
    networks:
      - voard-net
  voard_app:
    restart: always
    container_name: voard_app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
    ports:
      - 8787:80
    depends_on:
      - voard_db
    networks:
      - voard-net

networks:
  voard-net:
    driver: bridge